var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                  o                                             ",
   "                             ooooooo                                            ",
   "                        s         o                                             ",
   "                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                       ",
   "                                                        z                       ",
   "            xx                                          z                       ",
   "                                                        z      xx               ",
   "                                                        z               o       ",
   "                                                        z                       ",
   "                  xxxx     xx    xx                     z              xx       ",
   "                                                        z       o               ",
   "                                        xx              z                       ",
   "     x                                          o       z      xx      o        ",
   "     z                                        xx        z                       ",
   "     z                                   s              z              xx       ",
   "!!!xxz                           xx      xx             z                       ",
   "111z                      xx                            z      o                ",
   "111z               xx                                   z      xx               ",
   "111z         xx                                         z                       ",
   "111z   @     zz    s                                    z              N        ",
   "111zxxxxxxxxxzzxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!z!!!!!!!!!!!!!xxxx!!!!!!",
   "11111111111111111111111111111111111111111111111111111111111111111111111111111111"],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                        !!!       !!o       !                                     ",
   "                                            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                           ",
   "                                            z                                         z                           ",
   "                                            z                                         z                           ",
   "                                     xxxxxxxz                             s           zxxxxxxxx                   ",
   "                                     z                                                        z                   ",
   "                                     z                  o             s       s               z                   ",
   "      !  o                  xxxxxxxxxz                  x          xxxxxxxxxxxxxxxx           zxxxxxx             ",
   "      xxxxxxxxx                                         z          z              z                 z             ",
   "                         s                              z    N     z              z!                z             ",
   "                      xxxxxxx                           z!xxxxxxxx!z              zxxx              zxxxxxxx      ",
   "                            z                           zzzzzzzzzzzz                          x            z      ",
   "                            z!                                                                z            z      ",
   "                            zxxxxxxxxx                                 o          xxxxx   xxxxz            zxx    ",
   "                                     z                                            z   z   z                       ",
   "                                     z! o                     s                  !z                             o ",
   "                                     zxxx   xxxxxxxxxxxxx   xxxxx   xxxxxx   xxxxxz                        xxxxxxx",
   "                                        z   z           z   z   z   z    z   z                             zzzzzzz",
   "    @                                                                                                      zzzzzzz",
   "xxxxxxxxxxxxxxx                                                                                      xxxxxxzzzzzzz",
   "zzzzzzzzzzzzzzz                                   o                                                  zzzzzzzzzzzzz",
   "zzzzzzzzzzzzzzz                                                                                      zzzzzzzzzzzzz",
   "zzzzzzzzzzzzzzz       xxxxxxxxxxxxxxxxxx     xxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxzzzzzzzzzzzzz",
   "111111111111111!!!!!!!111111111111111111!!!!!11111111111!!!!!11111111111111111111!!!!!1111111111111111111111111111",
   "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                             o",
   "                                                                                                             x",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                         xxxxxxxxxx           ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                        xxxxxxxxxxx                           ",
   "                                                                          zzzzz                               ",
   "                                                                                                              ",
   "                                                               o                                              ",
   "                          o                                xxxxxxxx                                           ",
   "           xxxxxxxxxxxxxxxxxxxxxxxxxx                        zzzz                                             ",
   "                    zzzzzzzzzzzz                                                                              ",
   "                         zzzzz                                                                                ",
   "                            z                xxxxxx                                                           ",
   "    xxxxxx                  z                 zzzz                                                            ",
   "                            z                                                                                 ",
   "            s               z                                                                                 ",
   "                            z                                                                                 ",
   "               xxxxxx       z                                                                                 ",
   "                            z                                                              s                  ",
   "                            z                                                        xxxxx   xxxxxx           ",
   "                            z                                                        zzzzz   zzzzzz           ",
   "    xxxxxx                  z                                                        zzzzz   zzzzzz           ",
   "                            z                                                    !   zzzzz   zzzzzz           ",
   "                            z                                               xxxxxxxxxzzzzz   zzzzzz           ",
   "                            z                                               zzzzzzzzzzzzzz   zzzzzz           ",
   "               xxxxxx       z                                               zzzzzzzzzzzzzz   zzzzzz           ",
   "                            z                                         !   o zzzzzzzzzzzzzz   zzzzzz           ",
   "                            z                                   xxxxxxxxxxxxzzzzzzzzzzzzzz   zzzzzz           ",
   "                            z                                   zzzzzzzzzzzzzzzzzzzzzzzzzz   zzzzzz           ",
   "    xxxxxx                  z                                   zzzzzzzzzzzzzzzzzzzzzzzzzz   zzzzzz           ",
   "                            zo                   s       !      zzzzzzzzzzzzzzzzzzzzzzzzzz   zzzzzz           ",
   "                            zxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxzzzzzzzzzzzzzzzzzzzzzzzzzz   zzzzzz           ",
   "                            zzzzzzzzzzzzzzzzzzz     zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz   zzzzzz           ",
   "               xxxxxx       zzzzzzzzzzzzzzzzzzz     zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz   zzzzzz       N   ",
   "                            zzzzzzzzzzzzzzzzzzz     zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz   zzzzzz    xxxxxxx",
   "                            zzzzzzzzzzzzzzzzzzz     zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz   zzzzzz    zzzzzzz",
   "            @               zzzzzzzzzzzzzzzzzzz     zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz   zzzzzz    zzzzzzz",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxzzzzzzzzzzzzzzzzzzz     zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz   zzzzzz    zzzzzzz",
   "11111111111111111111111111111111111111111111111!!!!!11111111111111111111111111111111111111!!!111111!!!!1111111"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   " N   !  o   !                                                 o                                               ",
   "xxxxxxxxxxxxxxxxxx     xxxxxxxxx     xxxxxxxxxx     xxxxxxxxxxx     xxxxxxxx     xxxxxxxx                     ",
   "                 z     z       z  s  z        z  s  z         z  s  z      z     z                            ",
   "                 z!!!!!z       z     z        z     z         z     z      z!!!!!z                            ",
   "                 zxxxxxz       z     z        z     z         z     z      zxxxxxz         xxxx               ",
   "                               z     z        z     z         z     z                                         ",
   "                               z     z        z     z         z     z                                  o      ",
   "                               z!!!!!z        z     z         z!!!!!z                                xxxx     ",
   "                               zxxxxxz        z     z         zxxxxxz                            s            ",
   "                                              z     z                                                         ",
   "                                              z     z                                      xxxx               ",
   "                                              z!!!!!z                                                         ",
   "                                              zxxxxxz                                                         ",
   "     @           xxxxxxx                                                   xxxxxxx                            ",
   "                 zzzzzzz                                                   zzzzzzz                            ",
   "xxxxxxxxxxx      zzzzzzz                                                   zzzzzzz                            ",
   "zzzzzzzzzzz      zzzzzzz                                                   zzzzzzz                            ",
   "zzzzzzzzzzz      zzzzzzz       xxxxxxx                        xxxxxxx      zzzzzzz                            ",
   "zzzzzzzzzzz      zzzzzzz       zzzzzzz           s            zzzzzzz      zzzzzzz                            ",
   "zzzzzzzzzzz      zzzzzzz       zzzzzzz                        zzzzzzz      zzzzzzz                            ",
   "zzzzzzzzzzz      zzzzzzz       zzzzzzz           o            zzzzzzz      zzzzzzz                            ",
   "zzzzzzzzzzz      zzzzzzz       zzzzzzz        xxxxxxx         zzzzzzz      zzzzzzz                            ",
   "zzzzzzzzzzz      zzzzzzz       zzzzzzz        zzzzzzz         zzzzzzz      zzzzzzz                            ",
   "zzzzzzzzzzz      zzzzzzz       zzzzzzz        zzzzzzz         zzzzzzz      zzzzzzz                            ",
   "zzzzzzzzzzz      zzzzzzz       zzzzzzz        zzzzzzz         zzzzzzz      zzzzzzz                            ",
   "zzzzzzzzzzz!!!!!!zzzzzzz!!!!!!!zzzzzzz!!!!!!!!zzzzzzz!!!!!!!!!zzzzzzz!!!!!!zzzzzzz!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"],
  ["                                                 ",
   "                                                 ",
   "                                                 ",
   "                                                 ",
   "                                                 ",
   "                                                 ",
   "                                                 ",
   "                                                 ",
   "         x x  x  x x   x   x xxx x   x x         ",
   "         z z z z z z   z   z  z  zx  z z         ",
   "         zxz z z z z   z z z  z  z x z z         ",
   "          z  z z z z   zzzzz  z  z  xz           ",
   "          z   z  zzz    z z  zzz z   z z         ",
   "                                                 ",
   "                                                 ",
   "                                                 ",
   "                            x                    ",
   "                                                 ",
   "                                                 ",
   "  @                                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
   "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
   "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
